apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-house
  namespace: spring-application
  labels:
    app: test-house
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-house
  template:
    metadata:
      namespace: spring-application
      labels:
        app: test-house
    spec:
      containers:
        - name: test-house
          image: octavianuszzw/test-house:master
          imagePullPolicy: Always
          ports:
            - containerPort: 10200
          env:
            - name: GIT_COMMIT_ID
              value: {BUDIL_SIGN_ID}
      imagePullSecrets:
        - name: mydockerhubregistrykey